# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["CHLOEALANGSTON@GMAIL.COM"] %>
  email_provider_password: <%= ENV["DIZMANG2"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["CHLOEALANGSTON@GMAIL.COM"] %>
  secret_key_base: 07ed0d8bea6cdec15b3e1d7e550134ecf2d2e6eb63836ed7ed464bef648beb14909380103d5b5f14c8dd2d11daf0daa720dd67cad9a9544607de9fb3324db02c

test:
  secret_key_base: dd0ef5a55f84b307134a2e1bd47e42dabd9879f147dde32a19772372bdc3df520c2b960be1f2bc793a1babd4d6c35707879a6eb7696f93740462f97b71c3d1f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["CHLOEALANGSTON@GMAIL.COM"] %>
  email_provider_password: <%= ENV["DIZMANG2"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
